name: Build TCPDBench

on:
  push:
  pull_request:
  schedule:
    - cron: 42 8 * * */21

jobs:
  tcpdbench-docker:
    name: Check TCPDBench (docker)
    runs-on: ubuntu-latest
    container:
      volumes:
        - ./analysis/output:/TCPDBench/analysis/output

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: TCPDBench docker check
        uses: ./.github/workflows/
        with:
          entrypoint: "make clean && make results && git checkout ./analysis/output/rankplots/*.pdf && git diff --exit-code"
